# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 415)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 415))
        MainWindow.setMaximumSize(QtCore.QSize(400, 415))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_of_gui = QtWidgets.QLabel(self.centralwidget)
        self.name_of_gui.setGeometry(QtCore.QRect(0, 10, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.name_of_gui.setFont(font)
        self.name_of_gui.setAlignment(QtCore.Qt.AlignCenter)
        self.name_of_gui.setObjectName("name_of_gui")
        self.pusk_button = QtWidgets.QPushButton(self.centralwidget)
        self.pusk_button.setGeometry(QtCore.QRect(100, 300, 200, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pusk_button.setFont(font)
        self.pusk_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pusk_button.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pusk_button.setObjectName("pusk_button")
        self.mush_level = QtWidgets.QComboBox(self.centralwidget)
        self.mush_level.setGeometry(QtCore.QRect(20, 250, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.mush_level.setFont(font)
        self.mush_level.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mush_level.setObjectName("mush_level")
        self.mush_level.addItem("")
        self.mush_level.addItem("")
        self.mush_level.addItem("")
        self.mush_level.addItem("")
        self.sens_input_text = QtWidgets.QLineEdit(self.centralwidget)
        self.sens_input_text.setGeometry(QtCore.QRect(20, 70, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.sens_input_text.setFont(font)
        self.sens_input_text.setObjectName("sens_input_text")
        self.leveling_text = QtWidgets.QLabel(self.centralwidget)
        self.leveling_text.setGeometry(QtCore.QRect(20, 220, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.leveling_text.setFont(font)
        self.leveling_text.setObjectName("leveling_text")
        self.step_sens_text = QtWidgets.QLineEdit(self.centralwidget)
        self.step_sens_text.setGeometry(QtCore.QRect(20, 120, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.step_sens_text.setFont(font)
        self.step_sens_text.setObjectName("step_sens_text")
        self.kol_cycle = QtWidgets.QLineEdit(self.centralwidget)
        self.kol_cycle.setGeometry(QtCore.QRect(20, 170, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.kol_cycle.setFont(font)
        self.kol_cycle.setObjectName("kol_cycle")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализ ФП"))
        self.name_of_gui.setText(_translate(
            "MainWindow", "Формирователь ФП кода Баркера"))
        self.pusk_button.setText(_translate("MainWindow", "Запуск"))
        self.mush_level.setCurrentText(
            _translate("MainWindow", "0 уровень (-1; +1)"))
        self.mush_level.setItemText(0, _translate(
            "MainWindow", "0 уровень (-1; +1)"))
        self.mush_level.setItemText(1, _translate(
            "MainWindow", "1 уровень (-0.3; +0.3)"))
        self.mush_level.setItemText(2, _translate(
            "MainWindow", "2 уровень (-0.8...-0.3; +0.3...+0.8)"))
        self.mush_level.setItemText(3, _translate(
            "MainWindow", "3 уровень (-1...-0.8; +0.8...+1)"))
        self.sens_input_text.setPlaceholderText(
            _translate("MainWindow", "Введите чувствительность"))
        self.leveling_text.setText(_translate(
            "MainWindow", "Выберете уровень шума:"))
        self.step_sens_text.setPlaceholderText(_translate(
            "MainWindow", "Введите шаг снижения чувствительности"))
        self.kol_cycle.setPlaceholderText(_translate(
            "MainWindow", "Введите количество циклов передачи ФП"))

    def add_functions(self):
        self.pusk_button.clicked.connect(
            lambda: self.write_number(self.pusk_button.text()))

    def write_number(self, number):
        self.name_of_gui.setText('Тест кнопки')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
